//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderJourney
    {
        public int ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
