//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelItem
    {
        public int Id { get; set; }
        public Nullable<int> PanelID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<bool> Active { get; set; }
        public string html { get; set; }
        public string ImageLink { get; set; }
        public string ItemID { get; set; }
        public string Link { get; set; }
    
        public virtual Panel Panel { get; set; }
    }
}
