//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int Id { get; set; }
        public Nullable<System.Guid> TxnID { get; set; }
        public Nullable<System.Guid> CartID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<bool> GuestCheckout { get; set; }
        public Nullable<int> AddressID { get; set; }
    }
}
