//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<System.DateTime> TokenExpiry { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
