//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLog
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Transcript { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public string Link { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<long> ViewCount { get; set; }
    
        public virtual User User { get; set; }
    }
}
